# Custom site settings
title: Elliot Dickison
email: ejdickison@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elliotdickison.com" # the base hostname & protocol for your site
twitter_username: elliotdickison
github_username:  elliotdickison
google_plus_username:  elliotdickison
facebook_username: elliotdickison
gravatar_hash: 5a4ad376a72eeb6fd3a59400684d54bf
gravatar_size: 140

# Build settings
markdown: kramdown
sass:
    style: :compressed

# Blog posts get first-class urls
permalink: /:title