# Custom site settings
title: Elliot Dickison
email: your-email@domain.com
description: "Hey &mdash; I'm Elliot Dickison, a web developer currently working at Amazon.com in Seattle. I love to ski and spend time outdoors with my awesome wife and daughter."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elliotdickison.com" # the base hostname & protocol for your site
twitter_username: elliotdickison
github_username:  elliotdickison
gravatar: 5a4ad376a72eeb6fd3a59400684d54bf
gravatar_size: 140

# Build settings
markdown: kramdown
sass:
    style: :compressed

# Blog posts get first-class urls
permalink: /:title