# Site settings
title: Elliot Dickison
email: your-email@domain.com
description: > # web dev...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elliotdickison.com" # the base hostname & protocol for your site
twitter_username: elliotdickison
github_username:  elliotdickison

# Build settings
markdown: kramdown
